#!/usr/bin/bash

compiler="/usr/bin/gfortran-11"

ARGS=()
OUTPUT_ARG=""
INPUT_ARGS=("$@")
intercept_compilation=true
for ((i = 0; i <= $#; i++)); do
	var=${INPUT_ARGS[$i]}

	if [[ "$var" == "-c" ]]; then
		ARGS+=("$var")
		i=$((i + 1))
		var=${INPUT_ARGS[$i]}
		dirname=$(dirname -- "$var")
		filename=$(basename -- "$var")
		OUTPUT_ARG="${dirname}/${filename}.d"
		ARGS+=("$OUTPUT_ARG")
	fi

	if [[ "$var" == "-o" ]]; then
		ARGS+=("$var")
		i=$((i + 1))
		var=${INPUT_ARGS[$i]}
		dirname=$(dirname -- "$var")
		filename=$(basename -- "$var")
		OUTPUT_ARG="${dirname}/${filename}.d"
		ARGS+=("$OUTPUT_ARG")
	else
		ARGS+=("$var")
	fi
done

export IFS=' '
if [ "$intercept_compilation" == true ]; then
	#shopt -s nocasematch
	${compiler} "${@}"
	ret=$?
	if [ -z "$OUTPUT_ARG" ]; then
		echo "Missing output filename specification"
	else
		echo "Output file: $OUTPUT_ARG ${ARGS[@]}"
		${compiler} -E -dM ${ARGS[@]} >>"$OUTPUT_ARG"
	fi
else
	${compiler} "${@}"
	ret=$?
fi
exit $ret
